# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'
inhibit_all_warnings!

target 'Csa_Shop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Csa_Shop


pod 'SnapKit', '~> 3.2.0'
pod 'Alamofire', '~> 4.5.0'
pod 'ObjectMapper', '~> 2.2.7'
pod 'Kingfisher', '~> 3.10.2'
pod 'IQKeyboardManagerSwift', '~> 4.0.10'
pod 'ReSwift', '~> 4.0.0'

  target 'Csa_ShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Csa_ShopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target| target.build_configurations.each do |config| config.build_settings['ARCHS'] = "armv7 arm64" end   end
end

